[project]
name = "memoize_lib"
version = "0.1.0"
description = "Configurable memoization library for Python"
authors = [{name = "Your Name", email = "you@example.com"}]
requires-python = ">=3.10"

[tool.setuptools]
packages = ["memoize"]
